In [1]:
import pandas as pd

In [2]:
print("Oi")

Oi

In [3]:
df = pd.read_csv('pedidos_ecommerce.csv')

In [6]:
# print(df)
df.head(10)

,pedido_id,data_pedido,cliente_id,cidade,estado,categoria,produto,quantidade,preco_unitario,valor_total,desconto,valor_final,forma_pagamento,status
0,PED00001,2024-02-22,CLI9935,Goiânia,GO,Roupas,Camiseta Polo,3,82.04,246.12,0.00,246.12,cartão crédito,cancelado
1,PED00002,2024-11-04,CLI4257,São Paulo,SP,Livros,O Senhor dos Aneis,1,65.62,65.62,0.00,65.62,boleto,em transporte
2,PED00003,2024-01-04,CLI7924,Belo Horizonte,MG,Alimentos,Whey Protein 2kg,2,191.87,383.74,0.00,383.74,cartão débito,entregue
3,PED00004,2024-07-02,CLI5333,Salvador,BA,Calçados,Tenis Nike,3,285.77,857.31,0.00,857.31,cartão crédito,em transporte
4,PED00005,2024-10-09,CLI6925,Porto Alegre,RS,Brinquedos,Carrinho Hot Wheels,1,59.06,59.06,0.00,59.06,pix,entregue
5,PED00006,2024-02-21,CLI5554,Fortaleza,CE,Roupas,Camiseta Polo,2,129.58,259.16,33.25,225.91,pix,em transporte
6,PED00007,2024-12-15,CLI2169,Goiânia,GO,Beleza,Perfume Importado,3,201.71,605.13,63.70,541.43,pix,em transporte
7,PED00008,2024-11-23,CLI4598,Florianópolis,SC,Calçados,Bota Couro,2,249.02,498.04,0.00,498.04,boleto,entregue
8,PED00009,2024-02-03,CLI6155,Curitiba,PR,Eletrônicos,Smartphone Samsung,1,3051.61,3051.61,0.00,3051.61,cartão crédito,em transporte
9,PED00010,2024-10-14,CLI5304,Manaus,AM,Brinquedos,Boneca Barbie,4,97.14,388.56,0.00,388.56,boleto,cancelado

In [5]:
df.tail()

,pedido_id,data_pedido,cliente_id,cidade,estado,categoria,produto,quantidade,preco_unitario,valor_total,desconto,valor_final,forma_pagamento,status
4995,PED04996,2024-11-18,CLI1430,Rio de Janeiro,RJ,Informática,Mouse Gamer,2,293.68,587.36,35.78,551.58,pix,entregue
4996,PED04997,2024-02-01,CLI5667,Fortaleza,CE,Informática,Teclado Mecanico,3,373.63,1120.89,0.00,1120.89,pix,entregue
4997,PED04998,2024-07-01,CLI3778,Fortaleza,CE,Livros,Python para Dados,4,100.78,403.12,0.00,403.12,cartão débito,entregue
4998,PED04999,2024-06-05,CLI3543,Curitiba,PR,Alimentos,Whey Protein 2kg,3,129.27,387.81,37.74,350.07,cartão débito,entregue
4999,PED05000,2024-03-02,CLI3363,São Paulo,SP,Eletrônicos,Smart TV 50pol,5,3037.80,15189.00,0.00,15189.00,pix,entregue

In [7]:
df.shape

(5000, 14)

In [8]:
df.dtypes

pedido_id              str
data_pedido            str
cliente_id             str
cidade                 str
estado                 str
categoria              str
produto                str
quantidade           int64
preco_unitario     float64
valor_total        float64
desconto           float64
valor_final        float64
forma_pagamento        str
status                 str
dtype: object

In [9]:
# Salvar dataframe em diversos froamtos de arquivo

In [10]:
import os