In [1]:
import pandas as pd

In [2]:
print("Oi")

Oi

In [3]:
df = pd.read_csv('pedidos_ecommerce.csv')

In [4]:
# print(df)
df.head(10)

,pedido_id,data_pedido,cliente_id,cidade,estado,categoria,produto,quantidade,preco_unitario,valor_total,desconto,valor_final,forma_pagamento,status
0,PED00001,2024-02-22,CLI9935,Goiânia,GO,Roupas,Camiseta Polo,3,82.04,246.12,0.00,246.12,cartão crédito,cancelado
1,PED00002,2024-11-04,CLI4257,São Paulo,SP,Livros,O Senhor dos Aneis,1,65.62,65.62,0.00,65.62,boleto,em transporte
2,PED00003,2024-01-04,CLI7924,Belo Horizonte,MG,Alimentos,Whey Protein 2kg,2,191.87,383.74,0.00,383.74,cartão débito,entregue
3,PED00004,2024-07-02,CLI5333,Salvador,BA,Calçados,Tenis Nike,3,285.77,857.31,0.00,857.31,cartão crédito,em transporte
4,PED00005,2024-10-09,CLI6925,Porto Alegre,RS,Brinquedos,Carrinho Hot Wheels,1,59.06,59.06,0.00,59.06,pix,entregue
5,PED00006,2024-02-21,CLI5554,Fortaleza,CE,Roupas,Camiseta Polo,2,129.58,259.16,33.25,225.91,pix,em transporte
6,PED00007,2024-12-15,CLI2169,Goiânia,GO,Beleza,Perfume Importado,3,201.71,605.13,63.70,541.43,pix,em transporte
7,PED00008,2024-11-23,CLI4598,Florianópolis,SC,Calçados,Bota Couro,2,249.02,498.04,0.00,498.04,boleto,entregue
8,PED00009,2024-02-03,CLI6155,Curitiba,PR,Eletrônicos,Smartphone Samsung,1,3051.61,3051.61,0.00,3051.61,cartão crédito,em transporte
9,PED00010,2024-10-14,CLI5304,Manaus,AM,Brinquedos,Boneca Barbie,4,97.14,388.56,0.00,388.56,boleto,cancelado

In [5]:
df.tail()

,pedido_id,data_pedido,cliente_id,cidade,estado,categoria,produto,quantidade,preco_unitario,valor_total,desconto,valor_final,forma_pagamento,status
4995,PED04996,2024-11-18,CLI1430,Rio de Janeiro,RJ,Informática,Mouse Gamer,2,293.68,587.36,35.78,551.58,pix,entregue
4996,PED04997,2024-02-01,CLI5667,Fortaleza,CE,Informática,Teclado Mecanico,3,373.63,1120.89,0.00,1120.89,pix,entregue
4997,PED04998,2024-07-01,CLI3778,Fortaleza,CE,Livros,Python para Dados,4,100.78,403.12,0.00,403.12,cartão débito,entregue
4998,PED04999,2024-06-05,CLI3543,Curitiba,PR,Alimentos,Whey Protein 2kg,3,129.27,387.81,37.74,350.07,cartão débito,entregue
4999,PED05000,2024-03-02,CLI3363,São Paulo,SP,Eletrônicos,Smart TV 50pol,5,3037.80,15189.00,0.00,15189.00,pix,entregue

In [6]:
df.shape

(5000, 14)

In [7]:
df.dtypes

pedido_id              str
data_pedido            str
cliente_id             str
cidade                 str
estado                 str
categoria              str
produto                str
quantidade           int64
preco_unitario     float64
valor_total        float64
desconto           float64
valor_final        float64
forma_pagamento        str
status                 str
dtype: object

In [8]:
# Salvar dataframe em diversos froamtos de arquivo

In [9]:
import os

In [10]:
df.to_csv('pedidos.csv', index=False)

In [11]:
df.to_json('pedidos.json', orient='records', lines=True)

In [12]:
df.to_parquet('pedidos.parquet', index=False)

In [13]:
import pyarrow

In [14]:
print(pyarrow.__version__)

23.0.1

In [15]:
print(pyarrow.__version__)

23.0.1

In [16]:
print(pyarrow.__version__)

23.0.1

In [17]:
import pyarrow

print(pyarrow.__version__)

23.0.1

In [18]:
import pyarrow

print("PyArrow instalado com sucesso!")

PyArrow instalado com sucesso!

In [19]:
df.to_parquet('pedidos.parquet', index=False)

In [20]:
import pandas as pd
import pyarrow as pa

print("Pandas:", pd.__version__)
print("PyArrow:", pa.__version__)

Pandas: 3.0.3
PyArrow: 23.0.1

In [21]:
import pandas as pd
import pyarrow as pa

print(pd.__version__)
print(pa.__version__)
print(pd.__file__)
print(pa.__file__)

3.0.3
23.0.1
C:\Users\Claudia\miniconda3\envs\claupy\Lib\site-packages\pandas\__init__.py
C:\Users\Claudia\miniconda3\envs\claupy\Lib\site-packages\pyarrow\__init__.py

In [22]:
conda activate claupy

conda list pandas
conda list pyarrow
|

SyntaxError: invalid syntax (2675793070.py, line 1)

In [ ]:
import pandas as pd
print(pd.__version__)

In [ ]:
!conda list pandas

In [ ]:
!conda list pyarrow

In [ ]:
conda activate claupy

In [ ]:
!conda activate claupy

In [ ]:
for arquivo in arquivos:
    kb = os.path.getsize(arquivo) / 1024
    print(kb)

In [ ]:
import os

arquivos = os.listdir()

for arquivo in arquivos:
    print(arquivo)

In [ ]:
import os

arquivos = os.listdir()

for arquivo in arquivos:
    if os.path.isfile(arquivo):
        kb = os.path.getsize(arquivo) / 1024
        print(f"{arquivo}: {kb:.2f} KB")

In [ ]:
pip install duckdb

In [ ]:
import duckdb
import time
queries = {
'CSV': "SELECT cidade, SUM(valor_final) as total FROM 'pedidos.csv'
GROUP BY cidade ORDER BY total DESC",
'JSON': "SELECT cidade, SUM(valor_final) as total FROM 'pedidos.json'
GROUP BY cidade ORDER BY total DESC",
'Parquet': "SELECT cidade, SUM(valor_final)' as total FROM
'pedidos.parquet' GROUP BY cidade ORDER BY total DESC",
}
for nome, query in queries.items():
inicio = time.time()
resultado = duckdb.sql(query).df()
fim = time.time()
print(f'{nome:10s} {(fim - inicio)*1000:.2f} ms')

In [ ]:
import duckdb
import time

queries = {
    'CSV': """
        SELECT cidade, SUM(valor_final) as total
        FROM 'pedidos.csv'
        GROUP BY cidade
        ORDER BY total DESC
    """,

    'JSON': """
        SELECT cidade, SUM(valor_final) as total
        FROM 'pedidos.json'
        GROUP BY cidade
        ORDER BY total DESC
    """,

    'Parquet': """
        SELECT cidade, SUM(valor_final) as total
        FROM 'pedidos.parquet'
        GROUP BY cidade
        ORDER BY total DESC
    """
}

for nome, query in queries.items():
    inicio = time.time()
    resultado = duckdb.sql(query).df()
    fim = time.time()

    print(f'{nome:10s} {(fim - inicio)*1000:.2f} ms')

In [ ]:
import duckdb
import time
queries = {
'CSV': "SELECT cidade, SUM(valor_final) as total FROM 'pedidos.csv'
GROUP BY cidade ORDER BY total DESC",
'JSON': "SELECT cidade, SUM(valor_final) as total FROM 'pedidos.json'
GROUP BY cidade ORDER BY total DESC",
'Parquet': "SELECT cidade, SUM(valor_final) as total FROM
'pedidos.parquet' GROUP BY cidade ORDER BY total DESC",
}
for nome, query in queries.items():
inicio = time.time()
resultado = duckdb.sql(query).df()
fim = time.time()
print(f'{nome:10s} {(fim - inicio)*1000:.2f} ms')

In [23]:
import duckdb
import time

queries = {
    'CSV': """SELECT cidade, SUM(valor_final) as total
              FROM 'pedidos.csv'
              GROUP BY cidade
              ORDER BY total DESC""",

    'JSON': """SELECT cidade, SUM(valor_final) as total
               FROM 'pedidos.json'
               GROUP BY cidade
               ORDER BY total DESC""",

    'Parquet': """SELECT cidade, SUM(valor_final) as total
                  FROM 'pedidos.parquet'
                  GROUP BY cidade
                  ORDER BY total DESC"""
}

for nome, query in queries.items():
    inicio = time.time()
    resultado = duckdb.sql(query).df()
    fim = time.time()

    print(f'{nome:10s} {(fim - inicio)*1000:.2f} ms')

CSV        182.19 ms
JSON       122.96 ms
Parquet    13.23 ms